import type { Metadata } from "next"
import { LegalLayout } from "@/components/legal-layout"

export const metadata:Metadata={title:"Bantuan & Aturan",description:"Panduan penggunaan, aturan Ranked, dan transparansi ALZAVA Battle Point."}

export default function HelpPage(){
  return <LegalLayout eyebrow="Pusat Bantuan" title="Bantuan & Aturan ALZAVA Battle Point">
    <section><h2 className="text-xl font-black text-white">Apa itu ALZAVA Battle Point?</h2><p className="mt-2">ALZAVA Battle Point adalah platform latihan independen untuk membantu pengguna berlatih kemampuan yang relevan dengan persiapan SKD CASN, CPNS, BUMN, TIU, TWK, TKP, numerik, logika, dan penalaran. ALZAVA bukan situs resmi BKN, pemerintah, atau penyelenggara rekrutmen BUMN.</p></section>
    <section><h2 className="text-xl font-black text-white">Apa itu Quick Battle?</h2><p className="mt-2">Quick Battle adalah 5 soal singkat yang dapat dimainkan gratis tanpa login. Hasilnya berupa Preview Battle Point untuk pemanasan dan tidak masuk leaderboard resmi.</p></section>
    <section><h2 className="text-xl font-black text-white">Bagaimana cara masuk leaderboard?</h2><p className="mt-2">Buat akun peserta, lengkapi Nama Panggilan dan wilayah, lalu buka Ranked Battle. Setiap season menyediakan maksimal 3 Ranked Battle resmi. Satu Ranked berisi 30 soal dengan batas waktu 20 menit. Skor terbaik dari attempt yang selesai menjadi skor leaderboard pada season aktif.</p></section>
    <section><h2 className="text-xl font-black text-white">Bagaimana penentuan peringkat?</h2><p className="mt-2">Peringkat utama ditentukan oleh Battle Point. Jika dua atau lebih peserta memiliki Battle Point yang sama, peserta dengan waktu penyelesaian lebih cepat ditempatkan lebih tinggi. Leaderboard dapat dilihat pada tingkat nasional, provinsi, kabupaten/kota, dan kecamatan.</p></section>
    <section><h2 className="text-xl font-black text-white">Bagaimana kualitas soal Ranked dijaga?</h2><p className="mt-2">Generator Ranked menyaring tipe soal dasar yang terlalu mudah, mencegah prompt identik dalam season peserta, dan mencegah pola atau jenis soal yang sama muncul berulang dalam satu paket. Ranked diprioritaskan pada penalaran numerik, logika analitis, verbal, dan spasial tingkat menengah sampai sulit.</p></section>
    <section><h2 className="text-xl font-black text-white">Apa aturan saat Ranked?</h2><p className="mt-2">Kerjakan sendiri tanpa AI generatif, mesin pencari, kalkulator, catatan jawaban, atau bantuan orang lain. Jawaban disimpan otomatis secara berkala untuk mengurangi risiko kehilangan progress. Jika koneksi terganggu, peserta dapat melanjutkan attempt aktif selama batas waktunya belum habis.</p></section>
    <section><h2 className="text-xl font-black text-white">Apakah Ranked bisa dibeli?</h2><p className="mt-2">Selama Open Beta, semua pemain mendapat aturan dasar yang sama dan pembelian Ranked tambahan tidak dibuka. Jika kebijakan ini berubah pada fase berikutnya, aturan akan diumumkan secara jelas sebelum diberlakukan.</p></section>
    <section><h2 className="text-xl font-black text-white">Bagaimana season bekerja?</h2><p className="mt-2">Season resmi menggunakan urutan sederhana seperti Season 1, Season 2, Season 3, Season 4, dan seterusnya. Saat season ditutup, hasil final disimpan sebagai arsip dan season berikutnya dimulai dengan leaderboard serta kuota Ranked yang baru.</p></section>
    <section><h2 className="text-xl font-black text-white">Bagaimana kartu hasil dibagikan?</h2><p className="mt-2">Di halaman hasil pilih Bagikan Kartu Hasil. Sistem membuat kartu yang memuat Battle Point, prestasi, season, dan tantangan. Data akun pribadi seperti email tidak dimasukkan ke kartu publik.</p></section>
    <section><h2 className="text-xl font-black text-white">Bagaimana Chat Global, teman, dan pesan pribadi bekerja?</h2><p className="mt-2">Peserta yang login dapat menggunakan Chat Global, melihat profil pemain, mengirim permintaan pertemanan, dan berkirim pesan pribadi setelah berteman. Hindari spam dan jangan membagikan data pribadi sensitif.</p></section>
    <section><h2 className="text-xl font-black text-white">Poin saya tidak masuk leaderboard</h2><p className="mt-2">Pastikan Ranked berhasil dikirim, lolos pemeriksaan integritas, dan season masih aktif. Sistem memakai skor terbaik dari attempt resmi yang memenuhi syarat ranking.</p></section>
    <section><h2 className="text-xl font-black text-white">Apa itu Riwayat Season?</h2><p className="mt-2">Saat season resmi ditutup, Top 3 final disimpan sebagai arsip permanen. Podium season lama tidak berubah ketika season berikutnya dibuka, sehingga prestasi Champion tetap dapat dilihat pada profil dan riwayat season.</p></section>
  </LegalLayout>
}
