import type { Metadata } from "next"
import { LegalLayout } from "@/components/legal-layout"

export const metadata:Metadata={title:"Kebijakan Privasi",description:"Kebijakan privasi ALZAVA Battle Point."}

export default function PrivacyPage(){
  return <LegalLayout eyebrow="Privasi" title="Kebijakan Privasi">
    <section><h2 className="text-xl font-black text-white">Data yang kami proses</h2><p className="mt-2">ALZAVA Battle Point memproses data yang Anda berikan atau yang diperlukan untuk menjalankan layanan, seperti username, Nama Panggilan, wilayah, foto profil bila diunggah, token sesi peserta, jawaban dan hasil tes, riwayat tes, hubungan pertemanan, pesan Chat Global dan pesan pribadi, serta bukti pembayaran bila Anda membeli fitur digital.</p></section>
    <section><h2 className="text-xl font-black text-white">Tujuan penggunaan</h2><p className="mt-2">Data digunakan untuk membuat dan mengamankan akun, menjalankan tes, menghitung hasil, menampilkan leaderboard dan profil pemain, menyediakan fitur sosial, mencegah penyalahgunaan, memproses pembayaran, membuka fitur yang dibeli, menangani dukungan, serta mengukur kinerja produk secara agregat.</p></section>
    <section><h2 className="text-xl font-black text-white">Data yang tampil publik</h2><p className="mt-2">Nama Panggilan, avatar bila tersedia, wilayah, Battle Point, ketepatan, waktu, peringkat, dan prestasi dapat ditampilkan secara publik pada leaderboard atau profil pemain. Nilai atau estimasi IQ tidak ditampilkan pada leaderboard, podium, profil pemain publik, maupun kartu share.</p></section>
    <section><h2 className="text-xl font-black text-white">Chat dan pertemanan</h2><p className="mt-2">Pesan pada Chat Global dapat terlihat oleh peserta lain. Pesan pribadi hanya dimaksudkan untuk peserta dalam percakapan terkait dan pengelola yang memiliki kewenangan teknis bila diperlukan untuk keamanan, penanganan laporan, atau dukungan. Status online/presence dapat diproses untuk menampilkan aktivitas chat.</p></section>
    <section><h2 className="text-xl font-black text-white">Bukti pembayaran</h2><p className="mt-2">Pada tahap pembayaran manual, bukti pembayaran digunakan untuk verifikasi transaksi oleh admin. Transaksi peserta sekarang dikaitkan dengan sesi akun yang sedang login; Nama Panggilan tidak digunakan sebagai satu-satunya identitas penerima kredit. Hindari mengunggah informasi yang tidak diperlukan selain bukti transaksi terkait.</p></section>
    <section><h2 className="text-xl font-black text-white">Keamanan dan penyimpanan</h2><p className="mt-2">Kami menerapkan kontrol akses, token sesi, dan pemisahan data publik dengan data privat. Tidak ada sistem yang sepenuhnya bebas risiko; karena itu kami terus memperbaiki keamanan dan membatasi akses administratif.</p></section>
    <section><h2 className="text-xl font-black text-white">Hak pengguna</h2><p className="mt-2">Anda dapat memperbarui Nama Panggilan dan foto profil, menghapus foto profil, mengganti password, serta meminta koreksi informasi akun yang keliru. Mekanisme penghapusan akun mandiri akan disediakan pada pengembangan berikutnya; sementara itu pertanyaan mengenai data pribadi dapat disampaikan melalui halaman Bantuan.</p></section>
    <section><h2 className="text-xl font-black text-white">Catatan hasil tes</h2><p className="mt-2">Analisis kemampuan di ALZAVA Battle Point merupakan indikator performa dalam sistem permainan/latihan dan bukan diagnosis psikologis, hasil psikotes klinis, atau pengganti asesmen oleh psikolog berwenang.</p></section>
    <p className="text-xs text-slate-500">Terakhir diperbarui: 25 September 2026.</p>
  </LegalLayout>
}
