"use client"

import { useCallback, useEffect, useState } from "react"
import { Archive, CalendarPlus, Loader2, RefreshCw, RotateCcw, Trophy } from "lucide-react"
import { AdminTrafficMonitor } from "@/components/admin-traffic-monitor"

const API_URL = "https://efndozplpwyemzgqfnep.supabase.co/functions/v1/battle-season-admin"

type LiveSeason = { id?:string; season_number?:number; label?:string; starts_at?:string; ends_at?:string; status?:string; leaderboard_count?:number; is_test?:boolean; archive_enabled?:boolean; expired?:boolean }
type SeasonState = { live_season?:LiveSeason|null; history_count?:number }

async function seasonApi(body:Record<string,unknown>){const response=await fetch(API_URL,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"Kontrol season gagal diproses.");return data}

export function AdminSeasonControls({token}:{token:string}){
  const [state,setState]=useState<SeasonState>({});const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [label,setLabel]=useState("");const [durationHours,setDurationHours]=useState(168)
  const load=useCallback(async()=>{if(!token)return;setError("");try{const data=await seasonApi({action:"state",admin_token:token});setState(data.state||{})}catch(e){setError(e instanceof Error?e.message:"Status season belum dapat dimuat.")}},[token])
  useEffect(()=>{void load()},[load])
  async function run(action:"close"|"open"|"open_test"|"cancel_test"|"reset"){if(!token||busy)return;const live=state.live_season;if(action==="close"&&!window.confirm("Tutup season RESMI sekarang? Top 3 final akan disimpan ke History Ranking."))return;if(action==="cancel_test"&&!window.confirm("Tutup season TESTING tanpa menyimpan Top 3 ke History Ranking?"))return;if(action==="reset"&&window.prompt("Kosongkan leaderboard saja? Ketik RESET.")!=="RESET")return;if((action==="open"||action==="open_test")&&live)return;setBusy(true);setError("");setMessage("");try{const payload:Record<string,unknown>={action,admin_token:token};if(action==="open"||action==="open_test"){payload.label=label.trim();payload.duration_hours=action==="open_test"?Math.min(168,durationHours):durationHours}const data=await seasonApi(payload);if(action==="close")setMessage(`Season resmi ditutup. ${Number(data?.result?.winner_count||0)} juara disimpan.`);if(action==="cancel_test")setMessage("Season testing ditutup tanpa masuk History Ranking.");if(action==="reset")setMessage(`Ranking dibersihkan: ${Number(data?.result?.deleted_count||0)} entri.`);if(action==="open"||action==="open_test"){setMessage(action==="open"?"Season resmi baru dibuka.":"Season testing dibuka dan tidak akan masuk History Ranking.");setLabel("")}await load()}catch(e){setError(e instanceof Error?e.message:"Kontrol season gagal diproses.")}finally{setBusy(false)}}
  const live=state.live_season
  return <>
    <AdminTrafficMonitor token={token}/>
    <section className="mb-6 overflow-hidden rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-cyan-400/[.08] via-indigo-500/[.06] to-slate-950/40 p-5 shadow-2xl sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-cyan-300"><Trophy className="h-5 w-5"/><p className="text-xs font-black uppercase tracking-[.18em]">Kontrol Season</p></div><h2 className="mt-2 text-2xl font-black">Season resmi terpisah dari testing</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Season ditutup otomatis ketika deadline server tercapai. Season resmi mengarsipkan Top 3; season testing tidak pernah masuk History Ranking.</p></div><button onClick={()=>load()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-bold"><RefreshCw className={`h-4 w-4 ${busy?"animate-spin":""}`}/>Refresh</button></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
        <div className="rounded-2xl border border-white/10 bg-slate-950/45 p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Season Aktif</p>{live?<><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><p className="text-2xl font-black">{live.label||`Season ${live.season_number}`}</p><p className="mt-1 text-sm text-slate-400">{Number(live.leaderboard_count||0)} peserta · deadline {live.ends_at?new Date(live.ends_at).toLocaleString("id-ID"):"—"}</p></div><span className={`rounded-full border px-3 py-1.5 text-xs font-black uppercase ${live.is_test?"border-amber-300/20 bg-amber-300/10 text-amber-200":"border-emerald-300/20 bg-emerald-300/10 text-emerald-200"}`}>{live.is_test?"TESTING":"RESMI"}</span></div><div className="mt-5 flex flex-wrap gap-2">{live.is_test?<button onClick={()=>run("cancel_test")} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-3 text-sm font-black text-slate-950"><Archive className="h-4 w-4"/>Tutup Testing Tanpa Arsip</button>:<button onClick={()=>run("close")} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-3 text-sm font-black text-slate-950"><Archive className="h-4 w-4"/>Tutup Resmi + Arsip Top 3</button>}<button onClick={()=>run("reset")} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-rose-300/25 bg-rose-500/10 px-4 py-3 text-sm font-black text-rose-200"><RotateCcw className="h-4 w-4"/>Kosongkan Leaderboard</button></div></>:<div className="mt-3 rounded-xl border border-dashed border-white/15 bg-white/[.03] p-5 text-sm text-slate-400">Tidak ada season aktif.</div>}</div>
        <div className="rounded-2xl border border-white/10 bg-slate-950/45 p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Buka Season</p><span className="text-xs font-bold text-violet-300">{Number(state.history_count||0)} di history</span></div><label className="mt-4 grid gap-2 text-xs font-bold text-slate-400">Nama season (opsional)<input value={label} onChange={e=>setLabel(e.target.value)} disabled={Boolean(live)||busy} className="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white"/></label><label className="mt-3 grid gap-2 text-xs font-bold text-slate-400">Durasi (jam)<input type="number" min={1} max={720} value={durationHours} onChange={e=>setDurationHours(Math.max(1,Math.min(720,Number(e.target.value)||168)))} disabled={Boolean(live)||busy} className="rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white"/></label><div className="mt-4 grid gap-2"><button onClick={()=>run("open")} disabled={Boolean(live)||busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-3 text-sm font-black disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<CalendarPlus className="h-4 w-4"/>}Buka Season Resmi</button><button onClick={()=>run("open_test")} disabled={Boolean(live)||busy} className="rounded-xl border border-amber-300/25 bg-amber-300/10 px-4 py-3 text-sm font-black text-amber-100 disabled:opacity-40">Buka Season Testing · Tanpa History</button></div></div>
      </div>{message&&<div className="mt-4 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-100">{message}</div>}{error&&<div className="mt-4 rounded-xl border border-rose-300/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-100">{error}</div>}
    </section>
  </>
}
