"use client"

import { useEffect, useState } from "react"
import { ArrowRight, BarChart3, BrainCircuit, Clock3, Flame, History, Landmark, Shapes, Sigma, Swords, UsersRound } from "lucide-react"
import { SiteNavbar } from "@/components/site-navbar"
import { SiteFooter } from "@/components/site-footer"
import { BATTLE_API_URL, getParticipantToken } from "@/lib/battle"
import type { BattleParticipant } from "@/lib/battle"

export function SkdHub(){
  const [participant,setParticipant]=useState<BattleParticipant|null>(null)
  useEffect(()=>{const token=getParticipantToken();if(!token)return;fetch(BATTLE_API_URL,{headers:{"X-Battle-Token":token},cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setParticipant(d?.participant||null)).catch(()=>{})},[])
  return <div className="min-h-screen bg-[radial-gradient(circle_at_20%_-10%,rgba(34,211,238,.17),transparent_34rem),radial-gradient(circle_at_90%_10%,rgba(124,58,237,.14),transparent_30rem),linear-gradient(180deg,#020617,#07142e_55%,#020617)] text-white"><SiteNavbar participant={participant}/><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14">
    <section className="overflow-hidden rounded-[36px] border border-white/10 bg-[linear-gradient(135deg,rgba(34,211,238,.10),rgba(7,20,46,.86)_45%,rgba(124,58,237,.12))] p-7 shadow-[0_35px_120px_rgba(0,0,0,.35)] sm:p-10 lg:p-12"><span className="inline-flex rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.18em] text-emerald-200">Open Beta · Gratis</span><p className="mt-6 text-xs font-black uppercase tracking-[.22em] text-cyan-300">ALZAVA Learning Arena</p><h1 className="mt-3 max-w-4xl text-5xl font-black tracking-[-.055em] sm:text-6xl lg:text-7xl">Latihan SKD Lengkap.<br/><span className="text-indigo-300">TWK · TIU · TKP.</span></h1><p className="mt-6 max-w-3xl text-base leading-7 text-slate-300">Simulasi setengah paket SKD: 55 soal dalam 50 menit, terdiri dari 15 TWK, 25 TIU, dan 15 TKP. Skor per bagian, target latihan, autosave, dan review pembahasan tersedia setelah selesai.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/simulasi-skd" className="inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-500 via-blue-600 to-violet-600 px-6 py-3.5 font-black shadow-[0_0_34px_rgba(59,130,246,.26)]"><Swords className="h-5 w-5"/>Mulai Mini SKD 55 Soal</a><a href="/latihan-tiu" className="inline-flex items-center gap-2 rounded-2xl border border-cyan-300/20 bg-cyan-300/10 px-6 py-3.5 font-black text-cyan-100"><BrainCircuit className="h-5 w-5"/>Latihan TIU Khusus</a></div></section>

    <section className="mt-5"><a href="/riwayat-skd" className="group flex flex-col gap-5 rounded-[30px] border border-cyan-300/20 bg-[linear-gradient(120deg,rgba(34,211,238,.10),rgba(59,130,246,.07),rgba(124,58,237,.10))] p-6 shadow-[0_20px_70px_rgba(8,145,178,.08)] transition hover:-translate-y-1 hover:border-cyan-300/40 sm:flex-row sm:items-center sm:justify-between sm:p-7"><div className="flex items-start gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-200"><History className="h-7 w-7"/></span><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Hasil & perkembangan latihan</p><h2 className="mt-1 text-2xl font-black sm:text-3xl">Riwayat Mini SKD</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Lihat seluruh hasil latihan, skor /500, jumlah jawaban terbaik dari 55 soal, nilai TWK · TIU · TKP, pembahasan, serta bagikan hasil Anda.</p></div></div><span className="inline-flex shrink-0 items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 font-black text-slate-950">Buka Riwayat <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></a></section>

    <section className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-[28px] border border-emerald-300/15 bg-emerald-300/[.05] p-6"><Landmark className="h-7 w-7 text-emerald-300"/><p className="mt-4 text-xs font-black uppercase tracking-[.16em] text-emerald-300">TWK · 400 Item Aktif</p><h2 className="mt-2 text-2xl font-black">15 Soal per Simulasi</h2><p className="mt-2 text-sm leading-6 text-slate-400">Nasionalisme, Integritas, Bela Negara, Pilar Negara, dan Bahasa Indonesia dengan sumber rujukan tersimpan di bank soal.</p></div><div className="rounded-[28px] border border-cyan-300/15 bg-cyan-300/[.05] p-6"><BrainCircuit className="h-7 w-7 text-cyan-300"/><p className="mt-4 text-xs font-black uppercase tracking-[.16em] text-cyan-300">TIU · QIE1000</p><h2 className="mt-2 text-2xl font-black">25 Soal per Simulasi</h2><p className="mt-2 text-sm leading-6 text-slate-400">Numerik, logika, verbal, dan figural dari engine QIE1000 dengan prioritas soal yang belum pernah dilihat.</p></div><div className="rounded-[28px] border border-violet-300/15 bg-violet-300/[.05] p-6"><UsersRound className="h-7 w-7 text-violet-300"/><p className="mt-4 text-xs font-black uppercase tracking-[.16em] text-violet-300">TKP · 600 Skenario Aktif</p><h2 className="mt-2 text-2xl font-black">15 Soal per Simulasi</h2><p className="mt-2 text-sm leading-6 text-slate-400">Lima opsi bernilai 1–5 untuk Pelayanan Publik, Jejaring Kerja, Sosial Budaya, TIK, Profesionalisme, dan Anti-radikalisme.</p></div></section>

    <a href="/simulasi-skd" className="group mt-4 block rounded-[30px] border border-amber-300/18 bg-[linear-gradient(120deg,rgba(251,191,36,.08),rgba(124,58,237,.08))] p-6 transition hover:-translate-y-1 hover:border-amber-300/35 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">55 Soal · 50 Menit · Maks. 500</p><h2 className="mt-2 text-3xl font-black">Simulasi Mini SKD</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">15 TWK + 25 TIU + 15 TKP. Target latihan: TWK 35, TIU 60, TKP 55. Target ini hanya patokan latihan ALZAVA.</p></div><span className="inline-flex shrink-0 items-center gap-2 rounded-2xl bg-white px-5 py-3 font-black text-slate-950">Mulai <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></div></a>

    <section className="mt-8"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Latihan Fokus TIU</p><h2 className="mt-2 text-3xl font-black">Perkuat bagian tertentu</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <a href="/daily-training" className="group rounded-[28px] border border-orange-300/15 bg-orange-300/[.055] p-6 transition hover:-translate-y-1"><Flame className="h-6 w-6 text-orange-300"/><p className="mt-4 text-xs font-black uppercase text-orange-300">Setiap Hari</p><h3 className="mt-2 text-2xl font-black">TIU Harian</h3><p className="mt-2 text-sm leading-6 text-slate-400">5 soal cepat, pembahasan, dan streak harian.</p></a>
      <a href="/latihan-tiu?category=numerik" className="group rounded-[28px] border border-cyan-300/15 bg-cyan-300/[.05] p-6 transition hover:-translate-y-1"><Sigma className="h-6 w-6 text-cyan-300"/><p className="mt-4 text-xs font-black uppercase text-cyan-300">10 Soal</p><h3 className="mt-2 text-2xl font-black">Numerik</h3><p className="mt-2 text-sm leading-6 text-slate-400">Deret, persentase, aljabar, kerja, perbandingan, peluang.</p></a>
      <a href="/latihan-tiu?category=logika" className="group rounded-[28px] border border-violet-300/15 bg-violet-300/[.05] p-6 transition hover:-translate-y-1"><BrainCircuit className="h-6 w-6 text-violet-300"/><p className="mt-4 text-xs font-black uppercase text-violet-300">10 Soal</p><h3 className="mt-2 text-2xl font-black">Logika & Analitis</h3><p className="mt-2 text-sm leading-6 text-slate-400">Silogisme, inferensi, urutan, dan penalaran kritis.</p></a>
      <a href="/latihan-tiu?category=verbal" className="group rounded-[28px] border border-emerald-300/15 bg-emerald-300/[.05] p-6 transition hover:-translate-y-1"><BarChart3 className="h-6 w-6 text-emerald-300"/><p className="mt-4 text-xs font-black uppercase text-emerald-300">10 Soal</p><h3 className="mt-2 text-2xl font-black">Verbal</h3><p className="mt-2 text-sm leading-6 text-slate-400">Analogi konsep dan kosakata terpilih.</p></a>
      <a href="/latihan-tiu?category=figural" className="group rounded-[28px] border border-sky-300/15 bg-sky-300/[.05] p-6 transition hover:-translate-y-1"><Shapes className="h-6 w-6 text-sky-300"/><p className="mt-4 text-xs font-black uppercase text-sky-300">10 Soal</p><h3 className="mt-2 text-2xl font-black">Figural & Spasial</h3><p className="mt-2 text-sm leading-6 text-slate-400">Rotasi, arah, pola bentuk, simetri, dan spasial.</p></a>
      <a href="/simulasi-tiu" className="group rounded-[28px] border border-amber-300/15 bg-amber-300/[.055] p-6 transition hover:-translate-y-1"><Clock3 className="h-6 w-6 text-amber-300"/><p className="mt-4 text-xs font-black uppercase text-amber-300">35 Soal · 35 Menit</p><h3 className="mt-2 text-2xl font-black">Simulasi TIU</h3><p className="mt-2 text-sm leading-6 text-slate-400">Paket TIU campuran untuk menguji akurasi dan tempo.</p></a>
    </div></section>
    <section className="mt-8 rounded-[28px] border border-indigo-300/15 bg-indigo-300/[.05] p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-300">Dari latihan ke kompetisi</p><h2 className="mt-2 text-3xl font-black">Sudah siap menguji diri?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Ranked Battle memberi 3 kesempatan resmi per minggu. Skor terbaik masuk leaderboard kecamatan sampai nasional.</p></div><a href="/battle-test" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-2xl bg-white px-6 py-3.5 font-black text-slate-950"><Swords className="h-5 w-5"/>Masuk Ranked Battle</a></div></section><p className="mt-6 text-center text-xs leading-5 text-slate-600">Materi Latihan SKD ALZAVA adalah latihan mandiri, bukan soal resmi atau layanan resmi BKN.</p>
  </main><SiteFooter/></div>
}
