import type { Metadata } from "next"
import { LegalLayout } from "@/components/legal-layout"

export const metadata:Metadata={title:"Syarat & Ketentuan",description:"Syarat penggunaan ALZAVA Battle Point."}

export default function TermsPage(){
  return <LegalLayout eyebrow="Ketentuan" title="Syarat & Ketentuan">
    <section><h2 className="text-xl font-black text-white">Penggunaan layanan</h2><p className="mt-2">Dengan menggunakan ALZAVA Battle Point, Anda setuju memberikan informasi akun yang wajar, tidak mengganggu layanan, tidak menggunakan otomatisasi untuk memanipulasi hasil, dan tidak mencoba memperoleh akses ke data atau fungsi yang bukan hak Anda.</p></section>
    <section><h2 className="text-xl font-black text-white">Ranked Attempt Resmi</h2><p className="mt-2">Setiap peserta memperoleh 1 Ranked Attempt resmi gratis pada setiap season. Hanya hasil Ranked Attempt resmi tersebut yang dapat membentuk posisi leaderboard season. Aturan ini dibuat agar klasemen tidak berubah menjadi pay-to-win.</p></section>
    <section><h2 className="text-xl font-black text-white">Rematch / Practice Credit</h2><p className="mt-2">Setelah Ranked Attempt resmi digunakan, peserta dapat membeli Rematch / Practice Credit seharga Rp5.000 per kredit. Rematch tetap menghasilkan Battle Point, analisis hasil, dan riwayat perkembangan pribadi, tetapi tidak menggantikan skor resmi leaderboard pada season yang sama.</p></section>
    <section><h2 className="text-xl font-black text-white">Laporan Premium</h2><p className="mt-2">Laporan Premium dijual Rp5.000 untuk setiap hasil tes yang ingin dibuka secara premium. Pembayaran membuka analisis kemampuan lebih rinci, rekomendasi latihan, serta PDF pada hasil tersebut. Jika peserta menyelesaikan tes baru, laporan premium hasil baru dibuka secara terpisah. Produk ini merupakan fitur digital dan bukan laporan psikologi resmi.</p></section>
    <section><h2 className="text-xl font-black text-white">Fair play</h2><p className="mt-2">Ranked Attempt dimulai dengan 30 soal inti dalam 15 menit. Peserta dengan Battle Point inti 850 atau lebih akan diarahkan ke 10 soal High Range dengan tambahan waktu 8 menit untuk memverifikasi rentang skor atas. Peserta wajib mengerjakan sendiri dan dilarang menggunakan AI generatif, bot, kalkulator, mesin pencari, catatan jawaban, bantuan orang lain, atau cara lain yang memanipulasi hasil. Pengelola dapat meninjau atau membatalkan hasil yang memiliki indikasi penyalahgunaan berdasarkan bukti teknis yang tersedia.</p></section>
    <section><h2 className="text-xl font-black text-white">Privasi hasil</h2><p className="mt-2">Battle Point, nickname, avatar, wilayah, dan peringkat dapat tampil secara publik pada leaderboard atau kartu share. Estimasi IQ hanya ditampilkan pada area hasil pribadi dan tidak dipublikasikan pada podium, leaderboard, atau kartu share.</p></section>
    <section><h2 className="text-xl font-black text-white">Perubahan season dan layanan</h2><p className="mt-2">Soal, aturan season, metode skor, dan fitur dapat diperbaiki untuk meningkatkan kualitas. Perubahan material pada produk berbayar akan diupayakan tidak mengurangi hak digital yang sudah dibeli pada season terkait.</p></section>
    <section><h2 className="text-xl font-black text-white">Batasan hasil</h2><p className="mt-2">Battle Point dan estimasi IQ yang tersedia secara privat pada halaman hasil tidak boleh digunakan sebagai dasar tunggal untuk keputusan medis, psikologis, pendidikan, pekerjaan, atau keputusan berisiko tinggi lainnya.</p></section>
    <p className="text-xs text-slate-500">Terakhir diperbarui: 25 September 2026.</p>
  </LegalLayout>
}
