"use client"

import { FormEvent, useEffect, useState } from "react"

const API="https://efndozplpwyemzgqfnep.supabase.co/functions/v1/battle-recovery"
const PARTICIPANT_TOKEN_KEY="indonesia-battle-iq.participant-token.v1"

export default function ResetPasswordPage(){
  const [token,setToken]=useState("")
  const [password,setPassword]=useState("")
  const [confirm,setConfirm]=useState("")
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState("")
  const [done,setDone]=useState(false)
  const [kind,setKind]=useState("")
  useEffect(()=>{const p=new URLSearchParams(window.location.hash.replace(/^#/,""));setToken(p.get("access_token")||"");const q=new URLSearchParams(window.location.search);setKind(q.get("kind")||"")},[])
  async function submit(e:FormEvent){e.preventDefault();setError("");if(password.length<10){setError("Password baru minimal 10 karakter.");return}if(password!==confirm){setError("Konfirmasi password belum sama.");return}if(!token){setError("Tautan reset tidak valid atau sudah kedaluwarsa.");return}setBusy(true);try{const r=await fetch(API,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reset",kind,access_token:token,new_password:password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||"Password belum dapat diubah.");localStorage.removeItem("battle_admin_token");localStorage.removeItem(PARTICIPANT_TOKEN_KEY);setKind(d?.kind||kind);setDone(true);window.history.replaceState({},"",window.location.pathname)}catch(e){setError(e instanceof Error?e.message:"Password belum dapat diubah.")}finally{setBusy(false)}}
  const target=kind==="admin"?"/admin":"/account"
  return <main className="min-h-screen bg-[radial-gradient(circle_at_20%_0%,rgba(56,189,248,.16),transparent_32rem),linear-gradient(180deg,#020817,#07142f)] px-4 py-12 text-white"><div className="mx-auto max-w-lg"><a href="/battle" className="text-sm font-bold text-slate-400 hover:text-white">← ALZAVA Battle Point</a><section className="mt-6 rounded-3xl border border-white/10 bg-white/[.055] p-7 shadow-2xl backdrop-blur-xl"><img src="/alzava-emblem-v3.svg" alt="" className="mb-4 h-14 w-14"/><h1 className="text-3xl font-black">Buat Password Baru</h1><p className="mt-2 text-sm leading-6 text-slate-400">Link email membuktikan bahwa Anda memiliki alamat pemulihan yang terhubung ke akun ALZAVA.</p>{done?<div className="mt-6"><div className="rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-emerald-100">Password berhasil diganti. Semua sesi ALZAVA lama sudah tidak berlaku.</div><a href={target} className="mt-4 block rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-5 py-3 text-center font-black">Login kembali</a></div>:<form onSubmit={submit} className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-bold">Password baru<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} required autoComplete="new-password" className="rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3 outline-none focus:border-cyan-400/60"/></label><label className="grid gap-2 text-sm font-bold">Ulangi password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={10} required autoComplete="new-password" className="rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3 outline-none focus:border-cyan-400/60"/></label>{!token&&<div className="rounded-xl border border-amber-400/20 bg-amber-500/10 px-4 py-3 text-sm text-amber-100">Token belum ditemukan. Buka halaman ini dari link yang dikirim ke email Anda.</div>}{error&&<div className="rounded-xl border border-rose-400/20 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>}<button disabled={busy||!token} className="rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 px-5 py-3 font-black disabled:opacity-50">{busy?"Menyimpan...":"Simpan Password Baru"}</button></form>}</section></div></main>
}